import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#e8e6e1", 
  },
  scrollContent: {
    padding: 0,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 15,
    paddingHorizontal: 16,
    fontFamily:'AbhayaLibreExtraBold',
    backgroundColor: "#fff",
    width:'100%',
    borderBottomLeftRadius :20,
    borderBottomRightRadius : 20,
    alignSelf:'flex-start',
  },
  logo: {
    width: 150,
    height: 40,
  },
  headerText: {
    fontSize: 40,
    color: "#000",
    fontFamily: 'AbhayaLibreExtraBold',
  },
  headerText2: {
    fontSize: 40,
    color: "#3D5146",
    fontFamily: 'AbhayaLibreExtraBold',
  },
  avatar: {
    width: 50,
    height: 50,
    borderRadius: 30,
    backgroundColor: "#3D5146", 
  },
  cardIcon: {
    width: 60,
    height: 60,
    backgroundColor: "#fff", 
  },
  settingsIcon: {
    width: 24,
    height: 24,
  },
  mainCards: {
    flexDirection: "row",
    justifyContent: "center",
    marginVertical: 10,
    gap:-40,
    marginLeft:1
  },
  card: {
    flex: 1,
    padding: 8,
    backgroundColor: "#3D5146",
    margin: 16,
    borderRadius: 15,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    height: 110,
  },
  cardTitle: {
    fontSize: 18,
    color: "#ffffff",
    fontFamily: "AbhayaLibreExtraBold",
    textAlign: "center",
    marginTop: 0,
  },
  cardDescription: {
    fontSize: 10  ,
    color: "#ffffff",
    fontFamily: "AbhayaLibreExtraBold",
    textAlign: "center",
    marginTop: 10,
  },
  cardSubtitle: {
    fontSize: 12,
    color: "#ffffff",
    opacity: 0.8,
    textAlign: "center",
    marginTop: 5,
    fontFamily: "AbhayaLibreExtraBold",
  },
  cardIcon: {
    width: 40,
    height: 40,
    marginBottom: 10,
    tintColor: "#ffffff",
  },
  newsCard: {
    marginVertical: 10,
    padding: 10,
    backgroundColor: "#3D5146",
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    width:'92%',
    marginLeft:16,
    height:120,
    marginTop:-10,
  },
  newsImage: {
    width: 40,
    height: 40,
    marginLeft:150,
  },
  newsTitle: {
    fontSize: 27,
    marginVertical: 5,
    color: "#ffffff",
    fontFamily: "AbhayaLibreExtraBold",
    textAlign: "center",
  },
  newsDescription: {
    fontSize: 13,
    color: "#ffffff",
    opacity: 0.8,
    textAlign: "center",
    fontFamily: "AbhayaLibreExtraBold",
  },
  librarySection: {
    marginVertical: 15,
    backgroundColor: "#fff",
  },
  sectionTitle: {
    marginTop:25,
    marginLeft:30,
    fontSize: 30,
    marginBottom: 10,
    color: "#3D5146",
    fontFamily: "AbhayaLibreExtraBold",
  },
  libraryCards: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 20,
  },
  libraryCardOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#3D5146",
    padding: 10,
    alignItems: "center",
  },
  libraryCardText: {
    fontSize: 23,
    color: "#ffffff",
    fontFamily: "AbhayaLibreExtraBold",
    alignSelf:'center',
    marginTop:12,
  },
  chatButton: {
    paddingTop:-30,
    alignItems: "center",
    backgroundColor:'#DCD7D3',
    height:120
  },
  chatIcon: {
    width: 65,
    height: 65,
  },
  libraryCard: {
    width:190,
    height:280,
  },
  libraryImage: {
    height:'70%',
    width:'100%',
    resizeMode: 'cover',
    borderTopLeftRadius:20,
    borderTopRightRadius:20,
  },
});

export default styles;
